### ISSUE TITLE
how detect multiple object on same image

### ISSUE THREAD

**Issue by janaka1984** [rbgirshick/py-faster-rcnn#594] opened 2017-05-26 19:28 UTC
hi,

I have used following example https://huangying-zhan.github.io/2016/09/22/detection-faster-rcnn.html#Training%20on%20new%20dataset.

it can detect basketball, but I need to detect person also.
To do that I used person dataset with basketball dataset and changed train.txt and classes in basketball.py file

but it can not detect both object at once

what i need to change ?

thanks

**Comment by sulth** [comment] 2017-10-06 14:47
Have you got solution for multiple object detection within 1 frame.Please share me the tips.

**Comment by janaka1984** [comment] 2017-10-07 11:47
hi sulth,

call following block of code on main() 

------------------------------------------------------------------------------------------------
im = im[:, :, (2, 1, 0)]
fig, ax = plt.subplots(figsize=(12, 12))
 ax.imshow(im, aspect='equal')


for cls_ind, cls in enumerate(CLASSES[1:]):
        cls_ind += 1 # because we skipped background
        cls_boxes = boxes[:, 4*cls_ind:4*(cls_ind + 1)]
        cls_scores = scores[:, cls_ind]
        dets = np.hstack((cls_boxes,cls_scores[:, np.newaxis])).astype(np.float32)
        keep = nms(dets, NMS_THRESH)
        dets =  dets[keep, :]
        vis_detections(ax, cls, dets,  thresh=CONF_THRESH)


def vis_detections(ax, class_name , dets, thresh=0.5):
    """Draw detected bounding boxes."""
    inds = np.where(dets[:, -1] >= thresh)[0]
    print(inds)

    if len(inds) == 0:
          return
    for i in inds:
        bbox = dets[i, :4]
        score = dets[i, -1]
        print(bbox[0],bbox[1],bbox[2],bbox[3])
        ax.add_patch(
                     plt.Rectangle((bbox[0], bbox[1]),
                     bbox[2] - bbox[0],
                     bbox[3] - bbox[1], fill=False,
                     edgecolor='red', linewidth=3.5)
        )
        ax.text(bbox[0], bbox[1] - 2,
                '{:s} {:.3f}'.format(class_name, score),
                bbox=dict(facecolor='blue', alpha=0.5),
                fontsize=14, color='white')

    ax.set_title(('{} detections with '
                  'p({} | box) >= {:.1f}').format(class_name, class_name,  thresh), fontsize=14)
    plt.draw()

i hope you will get out put as you expect, try it :)

**Comment by sulth** [comment] 2017-10-08 06:57
Thank you so much for your response.

The demo.py has these statements included.But iam stuck with single object
detection with my own dataset (with only changes in the basketballdataset):

Iam incurring with an error at 20th iteration.

I1005 14:36:00.270619 24789 net.cpp:816] Ignoring source layer
bbox_pred_basketball
Solving...
I1005 14:36:01.191989 24789 solver.cpp:229] Iteration 0, loss = 1.03358
I1005 14:36:01.192062 24789 solver.cpp:245]     Train net output #0:
bbox_loss = 1.45159e-05 (* 1 = 1.45159e-05 loss)
I1005 14:36:01.192080 24789 solver.cpp:245]     Train net output #1:
cls_loss = 0.480214 (* 1 = 0.480214 loss)
I1005 14:36:01.192098 24789 solver.cpp:245]     Train net output #2:
rpn_cls_loss = 0.546922 (* 1 = 0.546922 loss)
I1005 14:36:01.192111 24789 solver.cpp:245]     Train net output #3:
rpn_loss_bbox = 0.0141369 (* 1 = 0.0141369 loss)
I1005 14:36:01.192128 24789 sgd_solver.cpp:106] Iteration 0, lr = 0.001
I1005 14:36:22.354821 24789 solver.cpp:229] Iteration 20, loss = 0.271491
I1005 14:36:22.354887 24789 solver.cpp:245]     Train net output #0:
bbox_loss = 0.000373775 (* 1 = 0.000373775 loss)
I1005 14:36:22.354904 24789 solver.cpp:245]     Train net output #1:
cls_loss = 0.0493833 (* 1 = 0.0493833 loss)
I1005 14:36:22.354918 24789 solver.cpp:245]     Train net output #2:
rpn_cls_loss = 0.148493 (* 1 = 0.148493 loss)
I1005 14:36:22.354931 24789 solver.cpp:245]     Train net output #3:
rpn_loss_bbox = 0.018571 (* 1 = 0.018571 loss)
I1005 14:36:22.354944 24789 sgd_solver.cpp:106] Iteration 20, lr = 0.001
Floating point exception (core dumped)

Do you have any idea on resolving it.

**Comment by sulth** [comment] 2017-10-08 13:46
Hi,
The error is as below:
Sir,i rebuild the FRCN caffe,thus reproduced the error above floating point
error: File "./tools/train_net.py", line 104, in <module>
    imdb, roidb = combined_roidb(args.imdb_name)
  File "./tools/train_net.py", line 69, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "./tools/train_net.py", line 66, in get_roidb
    roidb = get_training_roidb(imdb)
  File
"/home/ubuntu/customFRCN/py-faster-rcnn/tools/../lib/fast_rcnn/train.py",
line 122, in get_training_roidb
    rdl_roidb.prepare_roidb(imdb)
  File
"/home/ubuntu/customFRCN/py-faster-rcnn/tools/../lib/roi_data_layer/roidb.py",
line 27, in prepare_roidb
    roidb[i]['image'] = imdb.image_path_at(i)
IndexError: list index out of range

Is it due to the error on dataset creation?
Please can you share your dataset preperation details as well then?

**Comment by sulth** [comment] 2017-10-09 12:40
Hi,

I could now detect for 2 classes but only one image in one figure could be
tracked.How can i detect both classes in same image.May you please help me.

**Comment by sulth** [comment] 2017-10-09 17:39
Yes.I got it.Thanks alot:)

**Comment by aakarshmalhotra** [comment] 2017-11-07 07:39
Hi @janaka1984 

I can see that you have followed the blog:
https://huangying-zhan.github.io/2016/09/22/detection-faster-rcnn.html#Training%20on%20new%20dataset

I am trying to reproduce the same results, however, I can't find the codes for basketball.py, basketball_eval.py and any other files for using this dataset. However, I have downloaded the dataset. Can you please guide me through this.

Thanks in advance.

**Comment by Niladri365** [comment] 2018-01-04 13:38
I am looking for basketball.py and basketball_eval.py code. The annotations are also in .xml format instead of .txt format as INRIA person dataset. Would some body guide me in this regard?

**Comment by aakarshmalhotra** [comment] 2018-01-04 14:05
Hi @Niladri365 

You can find these files here:
https://github.com/Huangying-Zhan/py-faster-rcnn/tree/master/lib/datasets

Regards

**Comment by Niladri365** [comment] 2018-01-04 14:11
Thanks a lot...

**Closed** 2018-05-28 17:14 UTC

**Comment by Ram-Godavarthi** [comment] 2018-06-15 12:33
@janaka1984  @sulth  Can you share me the demo code where changes needs to done for getting 2 objects detection on single frame?. I tried your @janaka1984  solution. but i did not get it..
Could you please help me out..

Thank You
